/*
 * TileDB Storage Platform API
 *
 * TileDB Storage Platform REST API
 *
 * The version of the OpenAPI document: 2.2.19
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using TileDB.Cloud.Rest.Client;
using TileDB.Cloud.Rest.Api;
using TileDB.Cloud.Rest.Model;

namespace TileDB.Cloud.Rest.Test
{
    /// <summary>
    ///  Class for testing FilesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class FilesApiTests
    {
        private FilesApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new FilesApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FilesApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOf' FilesApi
            //Assert.IsInstanceOf(typeof(FilesApi), instance);
        }

        
        /// <summary>
        /// Test HandleCreateFile
        /// </summary>
        [Test]
        public void HandleCreateFileTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string _namespace = null;
            //FileCreate fileCreate = null;
            //string X_TILEDB_CLOUD_ACCESS_CREDENTIALS_NAME = null;
            //var response = instance.HandleCreateFile(_namespace, fileCreate, X_TILEDB_CLOUD_ACCESS_CREDENTIALS_NAME);
            //Assert.IsInstanceOf(typeof(FileCreated), response, "response is FileCreated");
        }
        
        /// <summary>
        /// Test HandleExportFile
        /// </summary>
        [Test]
        public void HandleExportFileTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string _namespace = null;
            //string file = null;
            //FileExport fileExport = null;
            //var response = instance.HandleExportFile(_namespace, file, fileExport);
            //Assert.IsInstanceOf(typeof(FileExported), response, "response is FileExported");
        }
        
    }

}
