/*
 * TileDB Storage Platform API
 *
 * TileDB Storage Platform REST API
 *
 * The version of the OpenAPI document: 2.2.19
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TileDB.Cloud.Rest.Api;
using TileDB.Cloud.Rest.Model;
using TileDB.Cloud.Rest.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TileDB.Cloud.Rest.Test
{
    /// <summary>
    ///  Class for testing ArraySharing
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ArraySharingTests
    {
        // TODO uncomment below to declare an instance variable for ArraySharing
        //private ArraySharing instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ArraySharing
            //instance = new ArraySharing();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ArraySharing
        /// </summary>
        [Test]
        public void ArraySharingInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ArraySharing
            //Assert.IsInstanceOf(typeof(ArraySharing), instance);
        }


        /// <summary>
        /// Test the property 'Actions'
        /// </summary>
        [Test]
        public void ActionsTest()
        {
            // TODO unit test for the property 'Actions'
        }
        /// <summary>
        /// Test the property 'Namespace'
        /// </summary>
        [Test]
        public void NamespaceTest()
        {
            // TODO unit test for the property 'Namespace'
        }
        /// <summary>
        /// Test the property 'NamespaceType'
        /// </summary>
        [Test]
        public void NamespaceTypeTest()
        {
            // TODO unit test for the property 'NamespaceType'
        }

    }

}
