/*
 * TileDB Storage Platform API
 *
 * TileDB Storage Platform REST API
 *
 * The version of the OpenAPI document: 2.2.19
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TileDB.Cloud.Rest.Api;
using TileDB.Cloud.Rest.Model;
using TileDB.Cloud.Rest.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TileDB.Cloud.Rest.Test
{
    /// <summary>
    ///  Class for testing Dimension
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DimensionTests
    {
        // TODO uncomment below to declare an instance variable for Dimension
        //private Dimension instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Dimension
            //instance = new Dimension();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Dimension
        /// </summary>
        [Test]
        public void DimensionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" Dimension
            //Assert.IsInstanceOf(typeof(Dimension), instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Domain'
        /// </summary>
        [Test]
        public void DomainTest()
        {
            // TODO unit test for the property 'Domain'
        }
        /// <summary>
        /// Test the property 'NullTileExtent'
        /// </summary>
        [Test]
        public void NullTileExtentTest()
        {
            // TODO unit test for the property 'NullTileExtent'
        }
        /// <summary>
        /// Test the property 'TileExtent'
        /// </summary>
        [Test]
        public void TileExtentTest()
        {
            // TODO unit test for the property 'TileExtent'
        }
        /// <summary>
        /// Test the property 'FilterPipeline'
        /// </summary>
        [Test]
        public void FilterPipelineTest()
        {
            // TODO unit test for the property 'FilterPipeline'
        }

    }

}
