/*
 * TileDB Storage Platform API
 *
 * TileDB Storage Platform REST API
 *
 * The version of the OpenAPI document: 2.2.19
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TileDB.Cloud.Rest.Api;
using TileDB.Cloud.Rest.Model;
using TileDB.Cloud.Rest.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TileDB.Cloud.Rest.Test
{
    /// <summary>
    ///  Class for testing GroupInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GroupInfoTests
    {
        // TODO uncomment below to declare an instance variable for GroupInfo
        //private GroupInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GroupInfo
            //instance = new GroupInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GroupInfo
        /// </summary>
        [Test]
        public void GroupInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" GroupInfo
            //Assert.IsInstanceOf(typeof(GroupInfo), instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Namespace'
        /// </summary>
        [Test]
        public void NamespaceTest()
        {
            // TODO unit test for the property 'Namespace'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Uri'
        /// </summary>
        [Test]
        public void UriTest()
        {
            // TODO unit test for the property 'Uri'
        }
        /// <summary>
        /// Test the property 'TiledbUri'
        /// </summary>
        [Test]
        public void TiledbUriTest()
        {
            // TODO unit test for the property 'TiledbUri'
        }
        /// <summary>
        /// Test the property 'AssetCount'
        /// </summary>
        [Test]
        public void AssetCountTest()
        {
            // TODO unit test for the property 'AssetCount'
        }
        /// <summary>
        /// Test the property 'GroupCount'
        /// </summary>
        [Test]
        public void GroupCountTest()
        {
            // TODO unit test for the property 'GroupCount'
        }
        /// <summary>
        /// Test the property 'Size'
        /// </summary>
        [Test]
        public void SizeTest()
        {
            // TODO unit test for the property 'Size'
        }
        /// <summary>
        /// Test the property 'LastAccessed'
        /// </summary>
        [Test]
        public void LastAccessedTest()
        {
            // TODO unit test for the property 'LastAccessed'
        }
        /// <summary>
        /// Test the property 'AllowedActions'
        /// </summary>
        [Test]
        public void AllowedActionsTest()
        {
            // TODO unit test for the property 'AllowedActions'
        }
        /// <summary>
        /// Test the property 'Logo'
        /// </summary>
        [Test]
        public void LogoTest()
        {
            // TODO unit test for the property 'Logo'
        }
        /// <summary>
        /// Test the property 'AccessCredentialsName'
        /// </summary>
        [Test]
        public void AccessCredentialsNameTest()
        {
            // TODO unit test for the property 'AccessCredentialsName'
        }
        /// <summary>
        /// Test the property 'ShareCount'
        /// </summary>
        [Test]
        public void ShareCountTest()
        {
            // TODO unit test for the property 'ShareCount'
        }
        /// <summary>
        /// Test the property 'PublicShare'
        /// </summary>
        [Test]
        public void PublicShareTest()
        {
            // TODO unit test for the property 'PublicShare'
        }
        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Test]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }
        /// <summary>
        /// Test the property 'LicenseId'
        /// </summary>
        [Test]
        public void LicenseIdTest()
        {
            // TODO unit test for the property 'LicenseId'
        }
        /// <summary>
        /// Test the property 'LicenseText'
        /// </summary>
        [Test]
        public void LicenseTextTest()
        {
            // TODO unit test for the property 'LicenseText'
        }

    }

}
