/*
 * TileDB Storage Platform API
 *
 * TileDB Storage Platform REST API
 *
 * The version of the OpenAPI document: 2.2.19
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TileDB.Cloud.Rest.Api;
using TileDB.Cloud.Rest.Model;
using TileDB.Cloud.Rest.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TileDB.Cloud.Rest.Test
{
    /// <summary>
    ///  Class for testing GroupBrowserFilterData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GroupBrowserFilterDataTests
    {
        // TODO uncomment below to declare an instance variable for GroupBrowserFilterData
        //private GroupBrowserFilterData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GroupBrowserFilterData
            //instance = new GroupBrowserFilterData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GroupBrowserFilterData
        /// </summary>
        [Test]
        public void GroupBrowserFilterDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" GroupBrowserFilterData
            //Assert.IsInstanceOf(typeof(GroupBrowserFilterData), instance);
        }


        /// <summary>
        /// Test the property 'Namespaces'
        /// </summary>
        [Test]
        public void NamespacesTest()
        {
            // TODO unit test for the property 'Namespaces'
        }

    }

}
