/*
 * TileDB Storage Platform API
 *
 * TileDB Storage Platform REST API
 *
 * The version of the OpenAPI document: 2.2.19
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TileDB.Cloud.Rest.Api;
using TileDB.Cloud.Rest.Model;
using TileDB.Cloud.Rest.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TileDB.Cloud.Rest.Test
{
    /// <summary>
    ///  Class for testing InvitationType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InvitationTypeTests
    {
        // TODO uncomment below to declare an instance variable for InvitationType
        //private InvitationType instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of InvitationType
            //instance = new InvitationType();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InvitationType
        /// </summary>
        [Test]
        public void InvitationTypeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" InvitationType
            //Assert.IsInstanceOf(typeof(InvitationType), instance);
        }



    }

}
