/*
 * TileDB Storage Platform API
 *
 * TileDB Storage Platform REST API
 *
 * The version of the OpenAPI document: 2.2.19
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TileDB.Cloud.Rest.Api;
using TileDB.Cloud.Rest.Model;
using TileDB.Cloud.Rest.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TileDB.Cloud.Rest.Test
{
    /// <summary>
    ///  Class for testing NotebookCopy
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NotebookCopyTests
    {
        // TODO uncomment below to declare an instance variable for NotebookCopy
        //private NotebookCopy instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of NotebookCopy
            //instance = new NotebookCopy();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NotebookCopy
        /// </summary>
        [Test]
        public void NotebookCopyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" NotebookCopy
            //Assert.IsInstanceOf(typeof(NotebookCopy), instance);
        }


        /// <summary>
        /// Test the property 'OutputUri'
        /// </summary>
        [Test]
        public void OutputUriTest()
        {
            // TODO unit test for the property 'OutputUri'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Namespace'
        /// </summary>
        [Test]
        public void NamespaceTest()
        {
            // TODO unit test for the property 'Namespace'
        }

    }

}
