/*
 * TileDB Storage Platform API
 *
 * TileDB Storage Platform REST API
 *
 * The version of the OpenAPI document: 2.2.19
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TileDB.Cloud.Rest.Api;
using TileDB.Cloud.Rest.Model;
using TileDB.Cloud.Rest.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TileDB.Cloud.Rest.Test
{
    /// <summary>
    ///  Class for testing RegisteredTaskGraphNode
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RegisteredTaskGraphNodeTests
    {
        // TODO uncomment below to declare an instance variable for RegisteredTaskGraphNode
        //private RegisteredTaskGraphNode instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RegisteredTaskGraphNode
            //instance = new RegisteredTaskGraphNode();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RegisteredTaskGraphNode
        /// </summary>
        [Test]
        public void RegisteredTaskGraphNodeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" RegisteredTaskGraphNode
            //Assert.IsInstanceOf(typeof(RegisteredTaskGraphNode), instance);
        }


        /// <summary>
        /// Test the property 'ClientNodeId'
        /// </summary>
        [Test]
        public void ClientNodeIdTest()
        {
            // TODO unit test for the property 'ClientNodeId'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'DependsOn'
        /// </summary>
        [Test]
        public void DependsOnTest()
        {
            // TODO unit test for the property 'DependsOn'
        }
        /// <summary>
        /// Test the property 'ArrayNode'
        /// </summary>
        [Test]
        public void ArrayNodeTest()
        {
            // TODO unit test for the property 'ArrayNode'
        }
        /// <summary>
        /// Test the property 'InputNode'
        /// </summary>
        [Test]
        public void InputNodeTest()
        {
            // TODO unit test for the property 'InputNode'
        }
        /// <summary>
        /// Test the property 'SqlNode'
        /// </summary>
        [Test]
        public void SqlNodeTest()
        {
            // TODO unit test for the property 'SqlNode'
        }
        /// <summary>
        /// Test the property 'UdfNode'
        /// </summary>
        [Test]
        public void UdfNodeTest()
        {
            // TODO unit test for the property 'UdfNode'
        }

    }

}
