/*
 * TileDB Storage Platform API
 *
 * TileDB Storage Platform REST API
 *
 * The version of the OpenAPI document: 2.2.19
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TileDB.Cloud.Rest.Api;
using TileDB.Cloud.Rest.Model;
using TileDB.Cloud.Rest.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TileDB.Cloud.Rest.Test
{
    /// <summary>
    ///  Class for testing UDFArrayDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UDFArrayDetailsTests
    {
        // TODO uncomment below to declare an instance variable for UDFArrayDetails
        //private UDFArrayDetails instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UDFArrayDetails
            //instance = new UDFArrayDetails();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UDFArrayDetails
        /// </summary>
        [Test]
        public void UDFArrayDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" UDFArrayDetails
            //Assert.IsInstanceOf(typeof(UDFArrayDetails), instance);
        }


        /// <summary>
        /// Test the property 'Uri'
        /// </summary>
        [Test]
        public void UriTest()
        {
            // TODO unit test for the property 'Uri'
        }
        /// <summary>
        /// Test the property 'Ranges'
        /// </summary>
        [Test]
        public void RangesTest()
        {
            // TODO unit test for the property 'Ranges'
        }
        /// <summary>
        /// Test the property 'Buffers'
        /// </summary>
        [Test]
        public void BuffersTest()
        {
            // TODO unit test for the property 'Buffers'
        }

    }

}
