/*
 * TileDB Storage Platform API
 *
 * TileDB Storage Platform REST API
 *
 * The version of the OpenAPI document: 2.2.19
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TileDB.Cloud.Rest.Api;
using TileDB.Cloud.Rest.Model;
using TileDB.Cloud.Rest.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TileDB.Cloud.Rest.Test
{
    /// <summary>
    ///  Class for testing UDFInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UDFInfoTests
    {
        // TODO uncomment below to declare an instance variable for UDFInfo
        //private UDFInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UDFInfo
            //instance = new UDFInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UDFInfo
        /// </summary>
        [Test]
        public void UDFInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" UDFInfo
            //Assert.IsInstanceOf(typeof(UDFInfo), instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Language'
        /// </summary>
        [Test]
        public void LanguageTest()
        {
            // TODO unit test for the property 'Language'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Readme'
        /// </summary>
        [Test]
        public void ReadmeTest()
        {
            // TODO unit test for the property 'Readme'
        }
        /// <summary>
        /// Test the property 'LicenseId'
        /// </summary>
        [Test]
        public void LicenseIdTest()
        {
            // TODO unit test for the property 'LicenseId'
        }
        /// <summary>
        /// Test the property 'LicenseText'
        /// </summary>
        [Test]
        public void LicenseTextTest()
        {
            // TODO unit test for the property 'LicenseText'
        }
        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Test]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }

    }

}
