/*
 * TileDB Storage Platform API
 *
 * TileDB Storage Platform REST API
 *
 * The version of the OpenAPI document: 2.2.19
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = TileDB.Cloud.Rest.Client.OpenAPIDateConverter;

namespace TileDB.Cloud.Rest.Model
{
    /// <summary>
    /// Object including array end_timestamps (list of Unix epoch timestamps in milliseconds) and pagination metadata
    /// </summary>
    [DataContract(Name = "ArrayEndTimestampData")]
    public partial class ArrayEndTimestampData : IEquatable<ArrayEndTimestampData>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ArrayEndTimestampData" /> class.
        /// </summary>
        /// <param name="endTimestamps">List of timestamps expressed in milliseconds since Unix epoch.</param>
        /// <param name="paginationMetadata">paginationMetadata.</param>
        public ArrayEndTimestampData(List<int> endTimestamps = default(List<int>), PaginationMetadata paginationMetadata = default(PaginationMetadata))
        {
            this.EndTimestamps = endTimestamps;
            this.PaginationMetadata = paginationMetadata;
        }

        /// <summary>
        /// List of timestamps expressed in milliseconds since Unix epoch
        /// </summary>
        /// <value>List of timestamps expressed in milliseconds since Unix epoch</value>
        [DataMember(Name = "end_timestamps", EmitDefaultValue = false)]
        public List<int> EndTimestamps { get; set; }

        /// <summary>
        /// Gets or Sets PaginationMetadata
        /// </summary>
        [DataMember(Name = "pagination_metadata", EmitDefaultValue = false)]
        public PaginationMetadata PaginationMetadata { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ArrayEndTimestampData {\n");
            sb.Append("  EndTimestamps: ").Append(EndTimestamps).Append("\n");
            sb.Append("  PaginationMetadata: ").Append(PaginationMetadata).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ArrayEndTimestampData);
        }

        /// <summary>
        /// Returns true if ArrayEndTimestampData instances are equal
        /// </summary>
        /// <param name="input">Instance of ArrayEndTimestampData to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ArrayEndTimestampData input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.EndTimestamps == input.EndTimestamps ||
                    this.EndTimestamps != null &&
                    input.EndTimestamps != null &&
                    this.EndTimestamps.SequenceEqual(input.EndTimestamps)
                ) && 
                (
                    this.PaginationMetadata == input.PaginationMetadata ||
                    (this.PaginationMetadata != null &&
                    this.PaginationMetadata.Equals(input.PaginationMetadata))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.EndTimestamps != null)
                {
                    hashCode = (hashCode * 59) + this.EndTimestamps.GetHashCode();
                }
                if (this.PaginationMetadata != null)
                {
                    hashCode = (hashCode * 59) + this.PaginationMetadata.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
