/*
 * TileDB Storage Platform API
 *
 * TileDB Storage Platform REST API
 *
 * The version of the OpenAPI document: 2.2.19
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = TileDB.Cloud.Rest.Client.OpenAPIDateConverter;

namespace TileDB.Cloud.Rest.Model
{
    /// <summary>
    /// File types represented as TileDB arrays
    /// </summary>
    /// <value>File types represented as TileDB arrays</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum FileType
    {
        /// <summary>
        /// Enum Notebook for value: notebook
        /// </summary>
        [EnumMember(Value = "notebook")]
        Notebook = 1,

        /// <summary>
        /// Enum Userdefinedfunction for value: user_defined_function
        /// </summary>
        [EnumMember(Value = "user_defined_function")]
        Userdefinedfunction = 2,

        /// <summary>
        /// Enum Mlmodel for value: ml_model
        /// </summary>
        [EnumMember(Value = "ml_model")]
        Mlmodel = 3,

        /// <summary>
        /// Enum File for value: file
        /// </summary>
        [EnumMember(Value = "file")]
        File = 4

    }

}
