/*
 * TileDB Storage Platform API
 *
 * TileDB Storage Platform REST API
 *
 * The version of the OpenAPI document: 2.2.19
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = TileDB.Cloud.Rest.Client.OpenAPIDateConverter;

namespace TileDB.Cloud.Rest.Model
{
    /// <summary>
    /// TileDB filter types
    /// </summary>
    /// <value>TileDB filter types</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum FilterType
    {
        /// <summary>
        /// Enum NONE for value: FILTER_NONE
        /// </summary>
        [EnumMember(Value = "FILTER_NONE")]
        NONE = 1,

        /// <summary>
        /// Enum GZIP for value: FILTER_GZIP
        /// </summary>
        [EnumMember(Value = "FILTER_GZIP")]
        GZIP = 2,

        /// <summary>
        /// Enum ZSTD for value: FILTER_ZSTD
        /// </summary>
        [EnumMember(Value = "FILTER_ZSTD")]
        ZSTD = 3,

        /// <summary>
        /// Enum LZ4 for value: FILTER_LZ4
        /// </summary>
        [EnumMember(Value = "FILTER_LZ4")]
        LZ4 = 4,

        /// <summary>
        /// Enum RLE for value: FILTER_RLE
        /// </summary>
        [EnumMember(Value = "FILTER_RLE")]
        RLE = 5,

        /// <summary>
        /// Enum BZIP2 for value: FILTER_BZIP2
        /// </summary>
        [EnumMember(Value = "FILTER_BZIP2")]
        BZIP2 = 6,

        /// <summary>
        /// Enum DOUBLEDELTA for value: FILTER_DOUBLE_DELTA
        /// </summary>
        [EnumMember(Value = "FILTER_DOUBLE_DELTA")]
        DOUBLEDELTA = 7,

        /// <summary>
        /// Enum BITWIDTHREDUCTION for value: FILTER_BIT_WIDTH_REDUCTION
        /// </summary>
        [EnumMember(Value = "FILTER_BIT_WIDTH_REDUCTION")]
        BITWIDTHREDUCTION = 8,

        /// <summary>
        /// Enum BITSHUFFLE for value: FILTER_BITSHUFFLE
        /// </summary>
        [EnumMember(Value = "FILTER_BITSHUFFLE")]
        BITSHUFFLE = 9,

        /// <summary>
        /// Enum BYTESHUFFLE for value: FILTER_BYTESHUFFLE
        /// </summary>
        [EnumMember(Value = "FILTER_BYTESHUFFLE")]
        BYTESHUFFLE = 10,

        /// <summary>
        /// Enum POSITIVEDELTA for value: FILTER_POSITIVE_DELTA
        /// </summary>
        [EnumMember(Value = "FILTER_POSITIVE_DELTA")]
        POSITIVEDELTA = 11

    }

}
