/*
 * TileDB Storage Platform API
 *
 * TileDB Storage Platform REST API
 *
 * The version of the OpenAPI document: 2.2.19
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = TileDB.Cloud.Rest.Client.OpenAPIDateConverter;

namespace TileDB.Cloud.Rest.Model
{
    /// <summary>
    /// Unit label
    /// </summary>
    /// <value>Unit label</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum PricingUnitLabel
    {
        /// <summary>
        /// Enum Byte for value: byte
        /// </summary>
        [EnumMember(Value = "byte")]
        Byte = 1,

        /// <summary>
        /// Enum Second for value: second
        /// </summary>
        [EnumMember(Value = "second")]
        Second = 2

    }

}
