/*
 * TileDB Storage Platform API
 *
 * TileDB Storage Platform REST API
 *
 * The version of the OpenAPI document: 2.2.19
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = TileDB.Cloud.Rest.Client.OpenAPIDateConverter;

namespace TileDB.Cloud.Rest.Model
{
    /// <summary>
    /// A report of the execution status of a node that ran on the client side. 
    /// </summary>
    [DataContract(Name = "TaskGraphClientNodeStatus")]
    public partial class TaskGraphClientNodeStatus : IEquatable<TaskGraphClientNodeStatus>, IValidatableObject
    {

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", EmitDefaultValue = false)]
        public ArrayTaskStatus? Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="TaskGraphClientNodeStatus" /> class.
        /// </summary>
        /// <param name="clientNodeUuid">clientNodeUuid.</param>
        /// <param name="status">status.</param>
        public TaskGraphClientNodeStatus(string clientNodeUuid = default(string), ArrayTaskStatus? status = default(ArrayTaskStatus?))
        {
            this.ClientNodeUuid = clientNodeUuid;
            this.Status = status;
        }

        /// <summary>
        /// Gets or Sets ClientNodeUuid
        /// </summary>
        [DataMember(Name = "client_node_uuid", EmitDefaultValue = false)]
        public string ClientNodeUuid { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TaskGraphClientNodeStatus {\n");
            sb.Append("  ClientNodeUuid: ").Append(ClientNodeUuid).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TaskGraphClientNodeStatus);
        }

        /// <summary>
        /// Returns true if TaskGraphClientNodeStatus instances are equal
        /// </summary>
        /// <param name="input">Instance of TaskGraphClientNodeStatus to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TaskGraphClientNodeStatus input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.ClientNodeUuid == input.ClientNodeUuid ||
                    (this.ClientNodeUuid != null &&
                    this.ClientNodeUuid.Equals(input.ClientNodeUuid))
                ) && 
                (
                    this.Status == input.Status ||
                    this.Status.Equals(input.Status)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ClientNodeUuid != null)
                {
                    hashCode = (hashCode * 59) + this.ClientNodeUuid.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Status.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
