/*
 * TileDB Storage Platform API
 *
 * TileDB Storage Platform REST API
 *
 * The version of the OpenAPI document: 2.2.19
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = TileDB.Cloud.Rest.Client.OpenAPIDateConverter;

namespace TileDB.Cloud.Rest.Model
{
    /// <summary>
    /// Response data for a task graph list, including pagination metadata.
    /// </summary>
    [DataContract]
    public partial class TaskGraphLogsData :  IEquatable<TaskGraphLogsData>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TaskGraphLogsData" /> class.
        /// </summary>
        /// <param name="taskGraphLogs">The requested task graph logs..</param>
        /// <param name="paginationMetadata">paginationMetadata.</param>
        public TaskGraphLogsData(List<TaskGraphLog> taskGraphLogs = default(List<TaskGraphLog>), PaginationMetadata paginationMetadata = default(PaginationMetadata))
        {
            this.TaskGraphLogs = taskGraphLogs;
            this.PaginationMetadata = paginationMetadata;
        }

        /// <summary>
        /// The requested task graph logs.
        /// </summary>
        /// <value>The requested task graph logs.</value>
        [DataMember(Name="task_graph_logs", EmitDefaultValue=false)]
        public List<TaskGraphLog> TaskGraphLogs { get; set; }

        /// <summary>
        /// Gets or Sets PaginationMetadata
        /// </summary>
        [DataMember(Name="pagination_metadata", EmitDefaultValue=false)]
        public PaginationMetadata PaginationMetadata { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TaskGraphLogsData {\n");
            sb.Append("  TaskGraphLogs: ").Append(TaskGraphLogs).Append("\n");
            sb.Append("  PaginationMetadata: ").Append(PaginationMetadata).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TaskGraphLogsData);
        }

        /// <summary>
        /// Returns true if TaskGraphLogsData instances are equal
        /// </summary>
        /// <param name="input">Instance of TaskGraphLogsData to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TaskGraphLogsData input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.TaskGraphLogs == input.TaskGraphLogs ||
                    this.TaskGraphLogs != null &&
                    input.TaskGraphLogs != null &&
                    this.TaskGraphLogs.SequenceEqual(input.TaskGraphLogs)
                ) && 
                (
                    this.PaginationMetadata == input.PaginationMetadata ||
                    (this.PaginationMetadata != null &&
                    this.PaginationMetadata.Equals(input.PaginationMetadata))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.TaskGraphLogs != null)
                    hashCode = hashCode * 59 + this.TaskGraphLogs.GetHashCode();
                if (this.PaginationMetadata != null)
                    hashCode = hashCode * 59 + this.PaginationMetadata.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
