/*
 * TileDB Storage Platform API
 *
 * TileDB Storage Platform REST API
 *
 * The version of the OpenAPI document: 2.2.19
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = TileDB.Cloud.Rest.Client.OpenAPIDateConverter;

namespace TileDB.Cloud.Rest.Model
{
    /// <summary>
    /// Copied udf uri and information
    /// </summary>
    [DataContract]
    public partial class UDFCopied :  IEquatable<UDFCopied>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UDFCopied" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UDFCopied() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="UDFCopied" /> class.
        /// </summary>
        /// <param name="outputUri">output location of the TileDB udf.</param>
        /// <param name="_namespace">namespace of the copied udf.</param>
        /// <param name="name">name of the copied udf.</param>
        /// <param name="id">unique ID of the copied udf (required).</param>
        public UDFCopied(string outputUri = default(string), string _namespace = default(string), string name = default(string), string id = default(string))
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new InvalidDataException("id is a required property for UDFCopied and cannot be null");
            }
            else
            {
                this.Id = id;
            }

            this.OutputUri = outputUri;
            this.Namespace = _namespace;
            this.Name = name;
        }

        /// <summary>
        /// output location of the TileDB udf
        /// </summary>
        /// <value>output location of the TileDB udf</value>
        [DataMember(Name="output_uri", EmitDefaultValue=false)]
        public string OutputUri { get; set; }

        /// <summary>
        /// namespace of the copied udf
        /// </summary>
        /// <value>namespace of the copied udf</value>
        [DataMember(Name="namespace", EmitDefaultValue=false)]
        public string Namespace { get; set; }

        /// <summary>
        /// name of the copied udf
        /// </summary>
        /// <value>name of the copied udf</value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// unique ID of the copied udf
        /// </summary>
        /// <value>unique ID of the copied udf</value>
        [DataMember(Name="id", EmitDefaultValue=true)]
        public string Id { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UDFCopied {\n");
            sb.Append("  OutputUri: ").Append(OutputUri).Append("\n");
            sb.Append("  Namespace: ").Append(Namespace).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as UDFCopied);
        }

        /// <summary>
        /// Returns true if UDFCopied instances are equal
        /// </summary>
        /// <param name="input">Instance of UDFCopied to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UDFCopied input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.OutputUri == input.OutputUri ||
                    (this.OutputUri != null &&
                    this.OutputUri.Equals(input.OutputUri))
                ) && 
                (
                    this.Namespace == input.Namespace ||
                    (this.Namespace != null &&
                    this.Namespace.Equals(input.Namespace))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.OutputUri != null)
                    hashCode = hashCode * 59 + this.OutputUri.GetHashCode();
                if (this.Namespace != null)
                    hashCode = hashCode * 59 + this.Namespace.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
