name: TileDB-Cloud-CSharp

on:
  push:
    tags: [ '*' ]
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Pack-TileDB-Cloud:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      # Checks out repository
      - uses: actions/checkout@v3

      # Limit GH runner environment to the one version of .NET that we install in next step
      - name: Remove existing .NET versions
        shell: bash
        run: |
          rm -rf $DOTNET_ROOT

      # Following action sets up dotnet and uses the strategy matrix to test on specific versions
      - name: Set up dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Display .NET versions
        run: dotnet --info

      - name: Pack TileDB.Cloud
        shell: bash
        run: dotnet pack -c Release TileDB.Cloud/TileDB.Cloud.csproj -o TileDB.Cloud/out

      - name: Upload TileDB.Cloud NuGet Package
        uses: actions/upload-artifact@v3
        with:
          name: TileDB.Cloud NuGet Package
          path: TileDB.Cloud/out/TileDB.Cloud.*.nupkg

  Test-TileDB-Cloud:
    needs: Pack-TileDB-Cloud
    strategy:
      fail-fast: false
      matrix:
        # Will be checking following versions
        dotnet: ['5.0', '6.0']
        # Repeat this test for each os
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      # Checks out repository
      - uses: actions/checkout@v3

      - name: Download TileDB.Cloud NuGet Artifact
        uses: actions/download-artifact@v3
        with:
          name: TileDB.Cloud NuGet Package
          path: TileDB.Cloud/out

      # Limit GH runner environment to the one version of .NET that we install in next step
      - name: Remove existing .NET versions
        shell: bash
        run: |
          rm -rf $DOTNET_ROOT

      # Following action sets up dotnet and uses the strategy matrix to test on specific versions
      - name: Set up dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Test TileDB.Cloud NuGet Package
        shell: bash
        run: dotnet test TileDB.Cloud.Test/TileDB.Cloud.Test.csproj
